app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  update-interval: 1m
  database-default-type: jpa

client:
  clients:
    github:
      base-url: https://api.github.com
      retry-policy:
        type: linear
        initial-interval: 1
        increment: 10
        max-attempts: 10
        retry-on-codes:
          - 429
    stackoverflow:
      base-url: https://api.stackexchange.com
      retry-policy:
        type: constant
        backoff-period: 10
        max-attempts: 100
        retry-on-codes:
          - 429
    scrapper:
      base-url: http://localhost:8090
      retry-policy:
        type: exponential
        initial-interval: 1
        multiplier: 2
        max-attemtps: 10
        retry-on-codes:
          - 429

ratelimit:
  capacity: 1000
  refill-rate: 100
  initial-tokens: 1000

spring:
  application:
    name: scrapper
  data-source:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  jpa:
    show-sql: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    enabled: true
