global:
  scrape_interval: 5s

scrape_configs:
  - job_name: scrapper
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8000
      - labels:
          application: scrapper

  - job_name: bot
    metrics_path: /metrics
    static_configs:
      - targets:
        - host.docker.internal:8001
      - labels:
          application: bot

